'use client';
import {useMemo,useState} from 'react';

type Row={id:string;source:string;row:number;name:string;date?:string|null;racquet?:string|null;main?:string|null;cross?:string|null;tension?:unknown;tensionMain?:unknown;tensionCross?:unknown;payment?:string;customerPrice?:unknown;received?:unknown;dueToMe?:unknown;cashHeld?:unknown;notes?:string|null};
type Adjustment={date:string;type:'supplied'|'purchase';amount:number};
const n=(v:unknown)=>typeof v==='number'?v:0;
const gbp=(v:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(v);
const displayDate=(v?:string|null)=>v?new Date(v).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'—';
const csvCell=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`;

export function AdminReports({rows,adjustments}:{rows:Row[];adjustments:Adjustment[]}){
 const [reportType,setReportType]=useState<'private'|'prostring'>('private'),[client,setClient]=useState('all'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[payment,setPayment]=useState('all');
 const sourceRows=rows.filter(r=>r.source===reportType);
 const clients=useMemo(()=>Array.from(new Set(sourceRows.map(r=>r.name.trim()).filter(Boolean))).sort((a,b)=>a.localeCompare(b)),[rows,reportType]);
 const report=useMemo(()=>sourceRows.filter(r=>(client==='all'||r.name.trim()===client)&&(!from||String(r.date||'')>=from)&&(!to||String(r.date||'')<=to)&&(payment==='all'||String(r.payment||'Unknown').toLowerCase()===payment)).sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))),[rows,reportType,client,from,to,payment]);
 const charged=report.reduce((s,r)=>s+n(r.customerPrice),0),received=report.reduce((s,r)=>s+n(r.received),0),balance=charged-received,cashHeld=report.reduce((s,r)=>s+n(r.cashHeld),0),dueBeforeAdjustments=report.reduce((s,r)=>s+n(r.dueToMe)-n(r.cashHeld),0),adjustmentTotal=adjustments.filter(item=>(!from||item.date>=from)&&(!to||item.date<=to)).reduce((sum,item)=>sum+(item.type==='supplied'?-item.amount:item.amount),0),dueToDM=dueBeforeAdjustments+adjustmentTotal;
 const download=()=>{const headings=reportType==='private'?['Job #','Date','Client','Racket','String setup','Tension','Charged','Received','Payment','Balance','Notes']:['Job #','Date','Client','Racket','String setup','Tension','Customer price','Payment','Cash held','Due to DM','Notes'];const lines=[headings.map(csvCell).join(','),...report.map(r=>(reportType==='private'?[r.row-2,r.date||'',r.name,r.racquet||'',[r.main,r.cross].filter(Boolean).join(' / '),r.tension??'',n(r.customerPrice),n(r.received),r.payment||'Unknown',n(r.customerPrice)-n(r.received),r.notes||'']:[r.row-1,r.date||'',r.name,r.racquet||'',[r.main,r.cross].filter(Boolean).join(' / '),r.tension??[r.tensionMain,r.tensionCross].filter(Boolean).join(' / '),n(r.customerPrice),r.payment||'Unknown',n(r.cashHeld),n(r.dueToMe)-n(r.cashHeld),r.notes||'']).map(csvCell).join(','))];const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=reportType==='prostring'?'prostring-work-report.csv':`${client==='all'?'all-private-clients':client.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-report.csv`;link.click();URL.revokeObjectURL(url)};
 return <section className="report-page"><div className="report-controls no-print"><label>Report<select value={reportType} onChange={e=>{setReportType(e.target.value as 'private'|'prostring');setClient('all');setPayment('all')}}><option value="private">Private clients</option><option value="prostring">ProString for Ray</option></select></label><label>Client<select value={client} onChange={e=>setClient(e.target.value)}><option value="all">{reportType==='private'?'All private clients':'All ProString clients'}</option>{clients.map(name=><option key={name}>{name}</option>)}</select></label><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Payment<select value={payment} onChange={e=>setPayment(e.target.value)}><option value="all">All payments</option>{reportType==='private'?<><option value="paid">Paid</option><option value="unpaid">Unpaid</option><option value="unknown">Unknown</option></>:<><option value="paid to ray">Paid to Ray</option><option value="paid cash">Paid Cash</option></>}</select></label><button className="secondary" onClick={download} disabled={!report.length}>Download CSV</button><button className="primary" onClick={()=>window.print()} disabled={!report.length}>Print report</button></div>
 <article className="report-sheet"><header><div><p className="eyebrow">STUDIO McLEOD · {reportType==='prostring'?'PROSTRING WORK REPORT':'STRINGING REPORT'}</p><h2>{reportType==='prostring'?(client==='all'?'Work completed for ProString':client):(client==='all'?'All private clients':client)}</h2><p>{reportType==='prostring'?'Prepared for Ray · ':''}{from||to?`${from?displayDate(from):'Beginning'} – ${to?displayDate(to):'Present'}`:'Complete order history'}</p></div><div className="report-mark">SM</div></header>{reportType==='private'?<div className="report-summary"><div><span>Jobs</span><strong>{report.length}</strong></div><div><span>Charged</span><strong>{gbp(charged)}</strong></div><div><span>Received</span><strong>{gbp(received)}</strong></div><div><span>Balance</span><strong className={balance>0?'balance-text-owed':balance<0?'balance-text-credit':''}>{balance===0?'—':`${gbp(Math.abs(balance))} ${balance>0?'owed':'credit'}`}</strong></div></div>:<div className="report-summary"><div><span>Jobs</span><strong>{report.length}</strong></div><div><span>Before adjustments</span><strong>{gbp(dueBeforeAdjustments)}</strong></div><div><span>Adjustments</span><strong>{adjustmentTotal>=0?'+ ':''}{gbp(adjustmentTotal)}</strong></div><div><span>Due to DM after adjustments</span><strong>{gbp(dueToDM)}</strong></div></div>}
 <div className="report-table"><div className="report-row report-row-head"><span>Date</span><span>Job #</span><span>{reportType==='prostring'?'Client / racket / strings':'Racket / strings'}</span><span>{reportType==='prostring'?'Customer price':'Charged'}</span><span>{reportType==='prostring'?'Payment':'Received'}</span><span>{reportType==='prostring'?'Cash held':'Payment'}</span><span>{reportType==='prostring'?'Due to DM':'Balance'}</span></div>{report.map(r=>{const owing=n(r.customerPrice)-n(r.received),shownTension=String(r.tension??([r.tensionMain,r.tensionCross].filter(Boolean).join(' / ')||'—'));return <div className="report-row" key={r.id}><span>{displayDate(r.date)}</span><span>{r.row-(reportType==='private'?2:1)}</span><span><strong>{reportType==='prostring'?`${r.name} · ${r.racquet||'—'}`:r.racquet||'—'}</strong><small>{[r.main,r.cross].filter(Boolean).join(' / ')||'—'} · {shownTension}</small></span><span>{gbp(n(r.customerPrice))}</span>{reportType==='prostring'?<><span>{r.payment||'Unknown'}</span><span>{n(r.cashHeld)?gbp(n(r.cashHeld)):'—'}</span><span>{gbp(n(r.dueToMe)-n(r.cashHeld))}</span></>:<><span>{gbp(n(r.received))}</span><span>{r.payment||'Unknown'}</span><span>{owing===0?'—':gbp(Math.abs(owing))+(owing>0?' owed':' credit')}</span></>}</div>})}</div>{!report.length?<div className="report-empty">No records match these report filters.</div>:null}<footer>Generated from your Studio McLeod Stringing Tracker</footer></article></section>
}
