'use client';
import {useMemo,useState} from 'react';

type Row={id:string;source:string;row:number;name:string;date?:string|null;racquet?:string|null;main?:string|null;cross?:string|null;tension?:unknown;payment?:string;customerPrice?:unknown;received?:unknown;notes?:string|null};
const n=(v:unknown)=>typeof v==='number'?v:0;
const gbp=(v:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(v);
const displayDate=(v?:string|null)=>v?new Date(v).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'—';
const csvCell=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`;

export function AdminReports({rows}:{rows:Row[]}){
 const privateRows=rows.filter(r=>r.source==='private');
 const clients=useMemo(()=>Array.from(new Set(privateRows.map(r=>r.name.trim()).filter(Boolean))).sort((a,b)=>a.localeCompare(b)),[rows]);
 const [client,setClient]=useState('all'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[payment,setPayment]=useState('all');
 const report=useMemo(()=>privateRows.filter(r=>(client==='all'||r.name.trim()===client)&&(!from||String(r.date||'')>=from)&&(!to||String(r.date||'')<=to)&&(payment==='all'||String(r.payment||'Unknown').toLowerCase()===payment)).sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))),[rows,client,from,to,payment]);
 const charged=report.reduce((s,r)=>s+n(r.customerPrice),0),received=report.reduce((s,r)=>s+n(r.received),0),balance=charged-received;
 const download=()=>{const headings=['Job #','Date','Client','Racket','String setup','Tension','Charged','Received','Payment','Balance','Notes'];const lines=[headings.map(csvCell).join(','),...report.map(r=>[r.row-2,r.date||'',r.name,r.racquet||'',[r.main,r.cross].filter(Boolean).join(' / '),r.tension??'',n(r.customerPrice),n(r.received),r.payment||'Unknown',n(r.customerPrice)-n(r.received),r.notes||''].map(csvCell).join(','))];const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${client==='all'?'all-private-clients':client.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-report.csv`;link.click();URL.revokeObjectURL(url)};
 return <section className="report-page"><div className="report-controls no-print"><label>Client<select value={client} onChange={e=>setClient(e.target.value)}><option value="all">All private clients</option>{clients.map(name=><option key={name}>{name}</option>)}</select></label><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Payment<select value={payment} onChange={e=>setPayment(e.target.value)}><option value="all">All payments</option><option value="paid">Paid</option><option value="unpaid">Unpaid</option><option value="unknown">Unknown</option></select></label><button className="secondary" onClick={download} disabled={!report.length}>Download CSV</button><button className="primary" onClick={()=>window.print()} disabled={!report.length}>Print report</button></div>
 <article className="report-sheet"><header><div><p className="eyebrow">STUDIO McLEOD · STRINGING REPORT</p><h2>{client==='all'?'All private clients':client}</h2><p>{from||to?`${from?displayDate(from):'Beginning'} – ${to?displayDate(to):'Present'}`:'Complete order history'}</p></div><div className="report-mark">SM</div></header><div className="report-summary"><div><span>Jobs</span><strong>{report.length}</strong></div><div><span>Charged</span><strong>{gbp(charged)}</strong></div><div><span>Received</span><strong>{gbp(received)}</strong></div><div><span>Balance</span><strong className={balance>0?'balance-text-owed':balance<0?'balance-text-credit':''}>{balance===0?'—':`${gbp(Math.abs(balance))} ${balance>0?'owed':'credit'}`}</strong></div></div>
 <div className="report-table"><div className="report-row report-row-head"><span>Date</span><span>Job #</span><span>Racket / strings</span><span>Charged</span><span>Received</span><span>Payment</span><span>Balance</span></div>{report.map(r=>{const owing=n(r.customerPrice)-n(r.received);return <div className="report-row" key={r.id}><span>{displayDate(r.date)}</span><span>{r.row-2}</span><span><strong>{r.racquet||'—'}</strong><small>{[r.main,r.cross].filter(Boolean).join(' / ')||'—'} · {String(r.tension??'—')}</small></span><span>{gbp(n(r.customerPrice))}</span><span>{gbp(n(r.received))}</span><span>{r.payment||'Unknown'}</span><span>{owing===0?'—':gbp(Math.abs(owing))+(owing>0?' owed':' credit')}</span></div>})}</div>{!report.length?<div className="report-empty">No records match these report filters.</div>:null}<footer>Generated from your Studio McLeod Stringing Tracker</footer></article></section>
}
