'use client';
import {useState} from 'react';

export type Adjustment={id:string;date:string;description:string;type:'supplied'|'purchase';amount:number};
export type Sundry={id:string;date:string;description:string;direction:'ray-owes'|'dm-owes';complete:boolean};
const gbp=(value:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(value);
const blank=():Adjustment=>({id:`adjustment-${Date.now()}`,date:new Date().toISOString().slice(0,10),description:'',type:'supplied',amount:0});
const blankSundry=():Sundry=>({id:`sundry-${Date.now()}`,date:new Date().toISOString().slice(0,10),description:'',direction:'ray-owes',complete:false});

export function ProStringAdjustments({items,onChange,sundries,onSundriesChange}:{items:Adjustment[];onChange:(items:Adjustment[])=>void;sundries:Sundry[];onSundriesChange:(items:Sundry[])=>void}){
 const [draft,setDraft]=useState<Adjustment|null>(null),[undo,setUndo]=useState<Adjustment[]|null>(null),[sundryDraft,setSundryDraft]=useState<Sundry|null>(null),[sundryUndo,setSundryUndo]=useState<Sundry[]|null>(null);
 const save=()=>{if(!draft||!draft.description.trim()||draft.amount<0)return;setUndo(items);onChange(items.some(x=>x.id===draft.id)?items.map(x=>x.id===draft.id?draft:x):[...items,draft]);setDraft(null)};
 const remove=(item:Adjustment)=>{setUndo(items);onChange(items.filter(x=>x.id!==item.id))};
 const saveSundry=()=>{if(!sundryDraft||!sundryDraft.description.trim())return;setSundryUndo(sundries);onSundriesChange(sundries.some(x=>x.id===sundryDraft.id)?sundries.map(x=>x.id===sundryDraft.id?sundryDraft:x):[...sundries,sundryDraft]);setSundryDraft(null)};
 const changeSundries=(next:Sundry[])=>{setSundryUndo(sundries);onSundriesChange(next)};
 return <section className="adjustments-card"><div className="adjustments-head"><div><p className="eyebrow">RAY BALANCE</p><h2>ProString adjustments</h2><p>String supplied by Ray reduces the balance. Purchases you make for ProString increase it.</p></div><div>{undo?<button className="secondary" onClick={()=>{onChange(undo);setUndo(null)}}>↶ Undo</button>:null}<button className="primary" onClick={()=>setDraft(blank())}>+ Add adjustment</button></div></div>
 <div className="adjustments-table"><div className="adjustment-row adjustment-header"><span>Date</span><span>Description</span><span>Type</span><span>Amount</span><span>Effect on amount due</span><span></span></div>{items.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(item=>{const effect=item.type==='supplied'?-item.amount:item.amount;return <div className="adjustment-row" key={item.id}><span>{new Date(item.date).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</span><strong>{item.description}</strong><span className={'adjustment-type '+item.type}>{item.type==='supplied'?'Supplied by Ray':'Purchased for ProString'}</span><span>{gbp(item.amount)}</span><span className={effect<0?'balance-text-owed':'balance-text-credit'}>{effect>0?'+':''}{gbp(effect)}</span><span className="adjustment-actions"><button className="edit-button" onClick={()=>setDraft({...item})}>Edit</button><button className="delete-button" onClick={()=>remove(item)}>Remove</button></span></div>})}</div>
 <section className="sundry-section"><div className="sundry-head"><div><h3>Sundry items</h3><p>Non-monetary things to remember between you and Ray. These do not affect the balance.</p></div><div>{sundryUndo?<button className="secondary small-action" onClick={()=>{onSundriesChange(sundryUndo);setSundryUndo(null)}}>↶ Undo</button>:null}<button className="secondary small-action" onClick={()=>setSundryDraft(blankSundry())}>+ Add item</button></div></div>{sundries.length?<div className="sundry-list">{sundries.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(item=><div className={'sundry-row '+(item.complete?'complete':'')} key={item.id}><button className="sundry-check" title={item.complete?'Mark as open':'Mark as complete'} onClick={()=>changeSundries(sundries.map(x=>x.id===item.id?{...x,complete:!x.complete}:x))}>{item.complete?'✓':'○'}</button><span className="sundry-date">{new Date(item.date).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</span><span className={'sundry-direction '+item.direction}>{item.direction==='ray-owes'?'Ray owes me':'I owe Ray'}</span><strong>{item.description}</strong><span className="adjustment-actions"><button className="edit-button" onClick={()=>setSundryDraft({...item})}>Edit</button><button className="delete-button" onClick={()=>changeSundries(sundries.filter(x=>x.id!==item.id))}>Remove</button></span></div>)}</div>:<div className="sundry-empty">No sundry items yet.</div>}</section>
 {draft?<div className="modal-backdrop" onMouseDown={()=>setDraft(null)}><form className="edit-modal adjustment-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();save()}}><div className="edit-head"><div><p className="eyebrow">PROSTRING ADJUSTMENT</p><h2>{items.some(x=>x.id===draft.id)?'Edit adjustment':'New adjustment'}</h2></div><button type="button" onClick={()=>setDraft(null)}>×</button></div><div className="edit-grid"><label>Date<input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>Type<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as Adjustment['type']})}><option value="supplied">Supplied by Ray</option><option value="purchase">Purchased for ProString</option></select></label><label className="wide">Description<input required value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Amount<input required min="0" step="0.01" type="number" value={draft.amount} onChange={e=>setDraft({...draft,amount:Number(e.target.value)})}/></label></div><div className="adjustment-preview">Effect on amount Ray owes you: <strong>{draft.type==='supplied'?'-':'+'}{gbp(draft.amount)}</strong></div><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setDraft(null)}>Cancel</button><button className="primary">Save adjustment</button></div></form></div>:null}
 {sundryDraft?<div className="modal-backdrop" onMouseDown={()=>setSundryDraft(null)}><form className="edit-modal adjustment-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();saveSundry()}}><div className="edit-head"><div><p className="eyebrow">SUNDRY ITEM</p><h2>{sundries.some(x=>x.id===sundryDraft.id)?'Edit item':'New item'}</h2></div><button type="button" onClick={()=>setSundryDraft(null)}>×</button></div><div className="edit-grid"><label>Date<input required type="date" value={sundryDraft.date} onChange={e=>setSundryDraft({...sundryDraft,date:e.target.value})}/></label><label>Who owes it?<select value={sundryDraft.direction} onChange={e=>setSundryDraft({...sundryDraft,direction:e.target.value as Sundry['direction']})}><option value="ray-owes">Ray owes me</option><option value="dm-owes">I owe Ray</option></select></label><label className="wide">Item or reminder<input required autoFocus value={sundryDraft.description} onChange={e=>setSundryDraft({...sundryDraft,description:e.target.value})}/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setSundryDraft(null)}>Cancel</button><button className="primary">Save item</button></div></form></div>:null}</section>
}
